import type { DeckConfig, DeckPreset } from "@/types";

export const DECK_PRESETS: Record<DeckPreset, DeckConfig> = {
  "command-center": {
    id: "command-center",
    name: "Command Center",
    description: "Full situational awareness — all widgets visible, globe prominent",
    layout: [
      { i: "globe", x: 0, y: 0, w: 8, h: 4, minW: 4, minH: 3 },
      { i: "intel-feed", x: 8, y: 0, w: 4, h: 4, minW: 3, minH: 2 },
      { i: "flights", x: 0, y: 4, w: 3, h: 2, minW: 2, minH: 2 },
      { i: "satellites", x: 3, y: 4, w: 3, h: 2, minW: 2, minH: 2 },
      { i: "fires", x: 6, y: 4, w: 3, h: 2, minW: 2, minH: 2 },
      { i: "weather", x: 9, y: 4, w: 3, h: 2, minW: 2, minH: 2 },
      { i: "earthquakes", x: 0, y: 6, w: 3, h: 2, minW: 2, minH: 2 },
      { i: "economy", x: 3, y: 6, w: 3, h: 2, minW: 2, minH: 2 },
      { i: "market", x: 6, y: 6, w: 3, h: 2, minW: 2, minH: 2 },
      { i: "energy", x: 9, y: 6, w: 3, h: 2, minW: 2, minH: 2 },
      { i: "deforestation", x: 0, y: 8, w: 3, h: 2, minW: 2, minH: 2 },
      { i: "health", x: 3, y: 8, w: 3, h: 2, minW: 2, minH: 2 },
      { i: "elections", x: 6, y: 8, w: 3, h: 2, minW: 2, minH: 2 },
      { i: "transparency", x: 9, y: 8, w: 3, h: 2, minW: 2, minH: 2 },
    ],
    visibleWidgets: [
      "globe",
      "intel-feed",
      "flights",
      "satellites",
      "fires",
      "weather",
      "earthquakes",
      "economy",
      "market",
      "energy",
      "deforestation",
      "health",
      "elections",
      "transparency",
    ],
  },

  "amazon-watch": {
    id: "amazon-watch",
    name: "Amazon Watch",
    description: "Environmental monitoring — fires, deforestation, weather",
    layout: [
      { i: "globe", x: 0, y: 0, w: 8, h: 5, minW: 4, minH: 3 },
      { i: "fires", x: 8, y: 0, w: 4, h: 3, minW: 3, minH: 2 },
      { i: "deforestation", x: 8, y: 3, w: 4, h: 2, minW: 3, minH: 2 },
      { i: "weather", x: 0, y: 5, w: 4, h: 3, minW: 3, minH: 2 },
      { i: "intel-feed", x: 4, y: 5, w: 4, h: 3, minW: 3, minH: 2 },
      { i: "earthquakes", x: 8, y: 5, w: 4, h: 3, minW: 3, minH: 2 },
    ],
    visibleWidgets: [
      "globe",
      "fires",
      "deforestation",
      "weather",
      "intel-feed",
      "earthquakes",
    ],
  },

  "brazil-pulse": {
    id: "brazil-pulse",
    name: "Brazil Pulse",
    description: "Socioeconomic overview — economy, markets, energy, health",
    layout: [
      { i: "economy", x: 0, y: 0, w: 4, h: 3, minW: 3, minH: 2 },
      { i: "market", x: 4, y: 0, w: 4, h: 3, minW: 3, minH: 2 },
      { i: "intel-feed", x: 8, y: 0, w: 4, h: 3, minW: 3, minH: 2 },
      { i: "energy", x: 0, y: 3, w: 4, h: 3, minW: 3, minH: 2 },
      { i: "health", x: 4, y: 3, w: 4, h: 3, minW: 3, minH: 2 },
      { i: "globe", x: 8, y: 3, w: 4, h: 3, minW: 3, minH: 3 },
      { i: "elections", x: 0, y: 6, w: 4, h: 2, minW: 3, minH: 2 },
      { i: "transparency", x: 4, y: 6, w: 4, h: 2, minW: 3, minH: 2 },
    ],
    visibleWidgets: [
      "economy",
      "market",
      "intel-feed",
      "energy",
      "health",
      "globe",
      "elections",
      "transparency",
    ],
  },

  custom: {
    id: "custom",
    name: "Custom",
    description: "Your saved layout",
    layout: [],
    visibleWidgets: [],
  },
};
